### PR TITLE
tweak VP8 video codec settings for 3g connections

### PR DESCRIPTION
**Pull request by zoff99**

### CODE REVIEW

**Comment by dvor** [comment]
Thanks! I didn't have time yet to do that myself. I'll try to integrate it and release new Antidote version before weekend.

**Comment by zoff99** [comment]
https://github.com/Antidote-for-Tox/objcTox/pull/171

**Comment by zoff99** [comment]
the other PR is more important for reliable video

**Comment by dvor** [comment]
Yep, I'll integrate both.

**Comment by zoff99** [comment]
nice ping me when there is something to test. i have a talk on friday ...

**Pull request merged**
